# file: global_costmap_params.yaml
global_costmap:
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: true
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}

# - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
